# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JARViss(object):
    def setupUi(self, JARViss):
        JARViss.setObjectName("JARViss")
        JARViss.setEnabled(True)
        JARViss.resize(1200, 700)
        JARViss.setMinimumSize(QtCore.QSize(500, 500))
        JARViss.setMaximumSize(QtCore.QSize(1200, 700))
        self.label = QtWidgets.QLabel(JARViss)
        self.label.setGeometry(QtCore.QRect(0, 0, 1200, 801))
        self.label.setMinimumSize(QtCore.QSize(500, 500))
        self.label.setMaximumSize(QtCore.QSize(16777213, 16777215))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("E:/New folder/blackky.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(JARViss)
        self.label_2.setGeometry(QtCore.QRect(0, 10, 185, 208))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("E:/New folder/8oXf.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(JARViss)
        self.label_3.setGeometry(QtCore.QRect(410, 120, 371, 361))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("E:/New folder/2RNb.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(JARViss)
        self.label_4.setGeometry(QtCore.QRect(550, 250, 91, 91))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("E:/New folder/V3lD.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(JARViss)
        self.label_5.setGeometry(QtCore.QRect(0, 460, 420, 235))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("E:/New folder/IMG_20230509_003135.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.textBrowser = QtWidgets.QTextBrowser(JARViss)
        self.textBrowser.setGeometry(QtCore.QRect(430, 10, 221, 41))
        self.textBrowser.setStyleSheet("background-color: transparent;\n"
"font: 700 8pt \"Segoe UI\";\n"
"border:none;")
        self.textBrowser.setObjectName("textBrowser")
        self.label_6 = QtWidgets.QLabel(JARViss)
        self.label_6.setGeometry(QtCore.QRect(40, 650, 241, 28))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("E:/New folder/Nt6v.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(JARViss)
        self.label_7.setGeometry(QtCore.QRect(1030, 20, 171, 105))
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("E:/New folder/QNBK.gif"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.terminalOutputBox = QtWidgets.QPlainTextEdit(JARViss)
        self.terminalOutputBox.setGeometry(QtCore.QRect(50, 525, 335, 80))
        self.terminalOutputBox.setStyleSheet("background-color: transparent;\n"
"color:green;\n"
"border:none;")
        self.terminalOutputBox.setObjectName("terminalOutputBox")
        self.label_8 = QtWidgets.QLabel(JARViss)
        self.label_8.setGeometry(QtCore.QRect(10, 360, 101, 71))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("E:/New folder/QNBH.gif"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(JARViss)
        self.pushButton.setGeometry(QtCore.QRect(1060, 580, 131, 101))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("font: 700 7pt \"Segoe UI\";\n"
"color:white;\n"
"border-image: url(E:/New folder/giphy 11.gif);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(JARViss)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 0, 101, 70))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("border-image: url(E:/New folder/TRIANGLE.png);\n"
"color:white;\n"
"font: 700 7pt \"Segoe UI\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_9 = QtWidgets.QLabel(JARViss)
        self.label_9.setGeometry(QtCore.QRect(1034, 420, 161, 141))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("E:/New folder/jvpicdcs.gif"))
        self.label_9.setScaledContents(True)
        self.label_9.setWordWrap(False)
        self.label_9.setObjectName("label_9")

        self.retranslateUi(JARViss)
        QtCore.QMetaObject.connectSlotsByName(JARViss)

    def retranslateUi(self, JARViss):
        _translate = QtCore.QCoreApplication.translate
        JARViss.setWindowTitle(_translate("JARViss", "JARVIS YOUR VIRTUAL VOICE ASSISTANT"))
        self.textBrowser.setHtml(_translate("JARViss", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:700; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt; font-weight:400;\"><br /></p></body></html>"))
        self.terminalOutputBox.setPlainText(_translate("JARViss", "->\n"
""))
        self.pushButton.setText(_translate("JARViss", "START"))
        self.pushButton_2.setText(_translate("JARViss", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JARViss = QtWidgets.QWidget()
    ui = Ui_JARViss()
    ui.setupUi(JARViss)
    JARViss.show()
    exit_code = app.exec_()
    sys.exit(exit_code)
  